Add Requires: gvfs - to fix not being able to delete files in tree
Atom requires gvfs in order to be able to send items to the trashbin, an error is caused without this package present.

Error: "The following file couldn't be moved to trash (is gvfs-trash installed?)"